config/routes.rb
Rails.application.routes.draw do

  root "projects#index"
  # get "/projects" => "projects#index"
  # get "/projects/new" => "projects#new"
  # get "/projects/:id" => "projects#show", as: "project"
  # get "/projects/:id/edit" => "projects#edit", as: "edit_project"
  # patch "/projects/:id" => "projects#update"

  resources :projects do
    resources :pledges
  end

end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  validates :name, presence: true
  validates :email, format: /\S+@\S+/
  AMOUNTS = [25, 50, 100, 200, 500]
  validates :amount, inclusion: { in: AMOUNTS }

  belongs_to :project

end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :pledges, dependent: :destroy
  has_attached_file :image, styles: {
    medium: "620x420>",
    small: "206x140>"
  }

  validates :name, :description, presence: true
  validates :description, length: { maximum: 500 }
  validates :target_pledge_amount, numericality: { greater_than: 0 }
  validates_attachment :image,
    content_type: { content_type: ['image/jpeg', 'image/png']},
    size: { less_than: 4.megabytes }
  validates :website, format: {
    with: /(((http|ftp|https):\/{2})+(([0-9a-z_-]+\.)+(aero|asia|biz|cat|com|coop|edu|gov|info|int|jobs|mil|mobi|museum|name|net|org|pro|tel|travel|ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|ax|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cx|cy|cz|cz|de|dj|dk|dm|do|dz|ec|ee|eg|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gb|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mn|mn|mo|mp|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|nom|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ra|rs|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sj|sk|sl|sm|sn|so|sr|st|su|sv|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yt|yu|za|zm|zw|arpa)(:[0-9]+)?((\/([~0-9a-zA-Z\#\+\%@\.\/_-]+))?(\?[0-9a-zA-Z\+\%@\/&\[\];=_-]+)?)?))\b/i,
    message: "must reference a valid URL"
  }


  def expired?
    pledging_ends_on < Date.today
  end

  def self.receiving_pledges
    Project.where("pledging_ends_on > ?", Time.now).order("pledging_ends_on")
  end

  def total_amount_pledged
    pledges.sum(:amount)
  end

  def amount_outstanding
    target_pledge_amount - total_amount_pledged
  end

  def funded?
    target_pledge_amount <= total_amount_pledged
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pledges_controller.rb
class PledgesController < ApplicationController

  before_action :set_project

  def index
    @pledges = @project.pledges
  end

  def new
    @pledge = @project.pledges.new
  end

  def create
    @pledge = @project.pledges.new(pledge_params)
    if @pledge.save
      redirect_to project_pledges_path(@project), notice: "Thank you for your pledge!"
    else
      render :new
    end
  end

private

  def pledge_params
    params.required(:pledge).permit(:name, :email, :amount, :comment)
  end

  def set_project
    @project = Project.find(params[:project_id])
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.receiving_pledges
  end

  def show
    @project = Project.find(params[:id])
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, notice: "Project successfully updated!"
    else
      render :edit
    end
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: "Project successfully created!"
    else
      render :new
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url, alert: "Project deleted."
  end

  private

    def project_params
      params.require(:project).permit(:name, :description, :target_pledge_amount, :pledging_ends_on, :website, :team_members, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pledges_helper.rb
module PledgesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def format_pledging_ends_on(project)
    if project.expired?
      content_tag(:strong, "All Done!")
    else
      distance_of_time_in_words(Date.today, project.pledging_ends_on) + " remaining"
    end
  end

  def image_for(project)
    if  project.image.exists?
      image_tag project.image.url(:medium)
    else
      image_tag 'placeholder.png'
    end
  end

  def format_goal(project)
    if project.funded?
      content_tag(:strong, "Funded")
    else
      number_to_currency(@project.amount_outstanding)
    end
  end
end

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2015 Todd Ruhlen |
    <%= link_to "Example Studio", "http://example.com" %>
  </p>
  <p>
    For educational purposes only.
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <div id="masthead">
    <h1><%= link_to 'Crowdfund', root_path %></h1>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li class="all-projects">
        <%= link_to "All Projects", projects_path, class: 'button' %>
      </li>
      <li class="create-project">
        <%= link_to "Add New Project", new_project_path, class: 'button' %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Crowdfund</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<div id="wrapper">
  <% flash.each do |key, value| %>
    <%= content_tag(:p, value, class: "flash #{key}") %>
    <!-- <p class= "flash <%= key %>">
      <%= flash[key] %>
    </p> -->
  <% end %>
  <div id="container">
    <%= render 'layouts/sidebar' %>
    <section id="content">
      <%= yield %>
    </section>
  </div>

</div>


<%= render 'layouts/footer' %>

</body>
</html>

app/views/pledges/index.html.erb
<header id="content-header">
  <h1>Pledges for <%= link_to @project.name, @project %></h1>
</header>


<ol id="pledges">
  <% @pledges.each do |pledge| %>
    <li>
      <span class="amount"><%= number_to_currency(pledge.amount) %></span>
      <span class="date"><%= time_ago_in_words(pledge.created_at) %> ago</span>
      <p>
        &quot;<%= pledge.comment %>&quot;
      </p>
    </li>
  <% end %>
</ol>

app/views/pledges/new.html.erb
<header id="content-header">
  <h1>Pledge for <%= link_to @project.name, @project %></h1>
</header>

<%= form_for([@project, @pledge]) do |f| %>
  <%= render "shared/errors", object: @pledge %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, size: 40, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :email %>
        <%= f.text_field :email, size: 40 %>
      </li>
      <li class="required">
        <%= f.label :amount %>
        <%= f.select :amount, Pledge::AMOUNTS, prompt: "Choose amount" %>
      </li>
      <li>
        <%= f.label :comment %>
        <%= f.text_area :comment, cols: 80, placeholder: "Let us know what you think about this project" %>
      </li>
    </ol>
    <p>
      <%= f.submit "Make Pledge" %>
      <%= link_to "Cancel", @project, class: "button" %>
    </p>
  </fieldset>
<% end %>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <%= render 'shared/errors', object: @project %>
  <fieldset>
    <ol>
      <li class="required">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true %>
      </li>
      <li class="required">
        <%= f.label :description %>
        <%= f.text_area :description, cols: 40, rows: 7 %>
      </li>
      <li class="required">
        <%= f.label :pledging_ends_on %>
        <%= f.date_select :pledging_ends_on %>
      </li>
      <li class="required">
        <%= f.label :target_pledge_amount %>
        <%= f.number_field :target_pledge_amount %>
      </li>
      <li class="required">
        <%= f.label :website %>
        <%= f.text_field :website, size: @project.website.respond_to?(:length) ? (@project.website.length + 10) : 50 %>
      </li>
      <li class="required">
        <%= f.label :team_members %>
        <%= f.text_field :team_members %>
      </li>
      <li class="required">
        <%= f.label :image %>
        <%= f.file_field :image %>
      </li>
      <li>
        <%= image_for @project %>
      </li>
    </ol>
    <p>
      <%= f.submit %>
      <%= link_to "Cancel", projects_path, class: 'button' %>
    </p>
  </fieldset>
<% end %>

app/views/projects/edit.html.erb
<header id="content-header">
  <h1>Editing <%= @project.name %></h1>
</header>

<%= render 'form' %>

app/views/projects/index.html.erb
<ul id="projects">
  <% @projects.each do |project| %>
    <li>
      <article class="project" id="<%= dom_id(project) %>">
        <header>
          <%= image_for(project) %>
          <h2><%= link_to(project.name, project) %></h2>
        </header>
        <p>
          <%= truncate(project.description, length: 150, separator: ' ') %>
        </p>
        <table>
          <tr>
            <th>Pledging Ends</th>
            <td><%= format_pledging_ends_on(project) %></td>
          </tr>
          <tr>
            <th>Goal</th>
            <td><%= number_to_currency(project.target_pledge_amount) %></td>
          </tr>
        </table>
      </article>
    </li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<header id="content-header">
  <h1>Add New Project</h1>
</header>

<%= render 'form' %>

app/views/projects/show.html.erb
<article id="project" class="project">
  <header>
    <%= image_for(@project) %>
    <h1><%= @project.name %></h1>
    <h2><%= format_pledging_ends_on(@project) %></h2>
  </header>
  <p>
    <%= @project.description %>
  </p>
  <h3>Remaining Goal</h3>
  <p>
    <%= format_goal(@project) %>
  </p>
  <h3>Website</h3>
  <p>
    <%= @project.website %>
  </p>
  <h3>Team Members</h3>
  <p>
    <%= @project.team_members %>
  </p>
  <%= link_to pluralize(@project.pledges.count, "Pledge"), project_pledges_url(@project) %>
  <footer>
    <% unless @project.funded? %>
      <%= link_to "Pledge!", new_project_pledge_path(@project), class: "button ok" %>
    <% end %>
    <nav>
      <%= link_to "Edit", edit_project_path, class: 'button' %> |
      <%= link_to "Delete", @project, class: 'button', method: :delete, data: { confirm: "Are you sure?" } %>
    </nav>
  </footer>
</article>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
<section id="errors">
  <header>
    <h2>
      Oops! The <%= object.class.name.titleize.downcase %> could not be saved.
    </h2>
    <h3>
      Please correct the following <%= pluralize(object.errors.count, "error") %>:
    </h3>
  </header>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</section>
<% end %>